FORMAT: 1A

# VUTTR

Repositório contendo informações sobre ferramentas utilizadas por desenvolvedores.

## Usuários [/users]

### Criar usuário [POST]

+ Request (application/json)

        [
            {
                "name": "Demo",
                "email": "demo@teste.com"
            }
        ]

+ Response 201 (application/json)

        [
            {
                "name": "Demo",
                "email": "demo@teste.com"
            }
        ]

## Sessão [/sessions]

### Criar Sessão [POST]

+ Request (application/json)

        {
            "email": "demo@teste.com"
        }

+ Response 200 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "user": {
                    "id": 12,
                    "name": "Demo",
                    "email": "demo@teste.com"
                 },
                 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTU3NDI3MDE2NiwiZXhwIjoxNTc0ODc0OTY2fQ.jmB1uhlGv-VVPslAinKx9r7d1gi1Odt5RfJYh5dwfQE"
            }

## Tools [/tools]

### Listar Tool [GET]

+ Headers

    Authorization: Bearer Token

+ Response 200 (application/json)

    [
        {
            "tags": [
                "api",
                "json",
                "schema",
                "node",
                "github",
                "rest"
            ],
            "_id": "5dd7eb963bb89d2ddb7eaaf5",
            "title": "json",
            "user": 12,
            "link": "https://github.com/typicode/json-server",
            "description": "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
            "createdAt": "2019-11-22T14:07:18.351Z",
            "updatedAt": "2019-11-22T14:07:18.351Z",
            "__v": 0
        }
    ]

### Criar Tool [POST]

+ Headers

    Authorization: Bearer Token

+ Request (application/json)

        {
            "title": "json",
            "link": "https://github.com/typicode/json-server",
            "description":"Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
            "tags": [
                "api",
                "json",
                "schema",
                "node",
                "github",
                "rest"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
              "tags": [
                "api",
                "json",
                "schema",
                "node",
                "github",
                "rest"
              ],
              "_id": "5dd7eb963bb89d2ddb7eaaf5",
              "title": "json",
              "user": 12,
              "link": "https://github.com/typicode/json-server",
              "description": "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
              "createdAt": "2019-11-22T14:07:18.351Z",
              "updatedAt": "2019-11-22T14:07:18.351Z",
              "__v": 0
            }

### Deletar Tool [DELETE/{id}]

+ Headers

    Authorization: Bearer Token

+ Request (application/json)

+ Response 204 (application/json)
