FORMAT: 1A

# VUTTR

Repositório contendo informações sobre ferramentas utilizadas por desenvolvedores.

# Group API

## Sobre [/]

Aqui podemos descrever detalhes que são comuns a todos os serviços como formatos, headers, tipos de erro, etc

# Group Users

## Users [/users]

### Criar usuário [POST]

+ Request criar usuário

  + Headers

          Accept: application/json
          Content-Type: application/json
  + Atributes (Users)

+ Response 201 (applicaton/json)
  + Atributes (Created)

# Group Sessions

## Sessions [/sessions]

## Autenticar usuário [POST]

+ Request autenticar usuário

  +Headers
          Accept: application/json
          Content-Type: application/json
